import pandas as pd
from transformer_training_data import DataPreparer
import xgboost as xgb
from sklearn.metrics import mean_absolute_error


ROLLING_PLAYER_STAT_COLS = [
    "points",
    "reboundstotal",
    "reboundsoffensive",
    "assists",
    "numminutes",
    "fieldgoalsmade",
    "fieldgoalsattempted",
    "threepointersmade",
    "threepointersattempted",
    "freethrowsmade",
    "freethrowsattempted",
    "steals",
    "blocks",
    "turnovers",
    "plusminuspoints",
    "foulspersonal",
]


PLAYER_FEATURE_COLS = [
    f"blended_std_{col}" for col in ROLLING_PLAYER_STAT_COLS
] + [
    "std_gmsc_baseline",
    "std_tsa_share_baseline",
    "std_expected_minutes",
]

# The individual player baseline stats you want to break out per teammate
TEAMMATE_STAT_COLS = [
    "std_gmsc_baseline",  # From your Game Score calculation
    "std_tsa_share_baseline",  # From your True Shooting Attempt Share calculation
]

TEAMMATE_FEATURE_COLS = [
    f"tm{teammate_num}_{stat}"
    for teammate_num in range(1, 5)
    for stat in TEAMMATE_STAT_COLS
]

TEAM_FEATURE_COLS = [
    "blended_std_ortg",
    "blended_std_drtg",
    "blended_std_win_pct",
    "blended_rolling_3_defensive_delta",
    "blended_rolling_10_defensive_delta",
    "is_b2b",
    "days_since_last_game",
]

OPPONENT_FEATURE_COLS = [
    "opp_rolling_3_ortg",
    "opp_rolling_10_ortg",
    "opp_blended_std_ortg",
    "opp_blended_std_drtg",
    "opp_blended_std_win_pct",
    "opp_blended_rolling_3_defensive_delta",
    "opp_blended_rolling_10_defensive_delta",
    "opp_is_b2b",
    "opp_days_since_last_game",
]



FEATURE_COLS = (
    PLAYER_FEATURE_COLS
    + TEAMMATE_FEATURE_COLS
    + TEAM_FEATURE_COLS
    + OPPONENT_FEATURE_COLS
)

TARGET_COLS = [
    "points",
    "numminutes",
    "assists", 
    "reboundstotal", 
]

datapreparer = DataPreparer()

# 1. Load Data
# Assuming 'df' is the full DataFrame generated by your TransformerDataGenerator
df = datapreparer.df.sort_values(by=['season', 'clean_game_datetime'])

# 2. Chronological Split (matching your existing deep learning split)
max_season = df['season'].max()
train_df = df[df['season'] <= max_season - 2]
train_df = train_df[train_df['numminutes'] > 12]
val_df = df[df['season'] == max_season - 1]
val_df = val_df[val_df['numminutes'] > 12]
test_df = df[df['season'] == max_season]
test_df = test_df[test_df['numminutes'] > 12]

# 3. Define Features and Target
# Use the exact same FEATURE_COLS list from transformer_training_data.py
features = FEATURE_COLS 
target = 'points'

X_train, y_train = train_df[features], train_df[target]
X_val, y_val = val_df[features], val_df[target]
X_test, y_test = test_df[features], test_df[target]

# 4. Initialize and Train XGBoost
# XGBoost can handle any missing values or NaNs natively without additional preprocessing[cite: 3].
model = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    objective='reg:absoluteerror', # Optimizes directly for median/MAE
    random_state=42
)

# Fit the model using the validation set for early stopping evaluation
model.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=50
)

# 5. Evaluate on Test Set
y_pred = model.predict(X_test)
test_mae = mean_absolute_error(y_test, y_pred)
print(f"XGBoost Test MAE: {test_mae:.3f}")